POST http://127.0.0.1:8080/userActionList
Content-type: application/json; charset=utf-8

[
  {"message_id": "11", "user_id": "us1", "action_type": 2},
  {"message_id": "12", "user_id": "us1", "action_type": 2},
  {"message_id": "41", "user_id": "us4", "action_type": 1},
  {"message_id": "42", "user_id": "us4", "action_type": 1},
  {"message_id": "43", "user_id": "us4", "action_type": 1},
  {"message_id": "13", "user_id": "us1", "action_type": 2},
  {"message_id": "14", "user_id": "us1", "action_type": 2}
]

###

GET http://127.0.0.1:8080/actionStats
